### ISSUE TITLE
Crash in models4mClusters1 on Mac/Linux with default readme parameters

### ISSUE THREAD

**Issue by dhakim87** [LewisLabUCSD/StanDep#10]
Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in models4mClusters1>writeMyMatrix (line 168)
    fprintf(fid,'%0.2f\t',A(ii,:));

Error in models4mClusters1 (line 97)
writeMyMatrix(J,strcat(folderName,'/Call.txt'));

--  This is just a platform difference.  "/Call.txt" refers to current folder on windows, but root folder on mac/linux.  Consider defaulting the output directory to the current directory with an absolute path.

**Comment by cjos238** [comment]
It is left empty only if the text files are not required by the user. If one wants to use the current working directory to write files in, the path must be provided. I have fixed this in the code annotations and Call.txt now also requires mentioning the path.
